module_order:
  - 'fastp'
  - 'picard'
  - 'samtools'
  - 'bcftools'

picard_config:
  s_name_filenames: True

extra_fn_clean_exts:
  - ".alignment"
  - ".base_distribution_by_cycle"
  - ".dedup"
  - ".gcbias_detail"
  - ".gcbias_summary"
  - ".insert_size"
  - ".mean_quality_by_cycle"
  - ".quality_yield"
  - ".qualityscore"

highlight_patterns:
  - "PBAC"
  - "PDOM"
  - "PHIS"
  - "PITA"
  - "PMON"

highlight_colors:
  - "#000080"
  - "#1E90FF"
  - "#8B0000"
  - "#FFD700"
  - "#008B00"
