title: "genotyping_pipeline"
subtitle: "UiO Ecological and Evolutionary Genomics Group"
intro_text: "This report summarises statistics from the genotyping pipeline by searching the output directory."
show_analysis_time: true
show_analysis_paths: false

custom_logo: "sparrows.jpg"
custom_logo_url: "https://github.com/EcoEvoGenomics"
custom_logo_title: "Visit our GitHub: https://github.com/EcoEvoGenomics"

highlight_patterns:
  - "PBAC"
  - "PDOM"
  - "PHIS"
  - "PITA"
  - "PMON"

highlight_colors:
  - "#000080"
  - "#1E90FF"
  - "#8B0000"
  - "#FFD700"
  - "#008B00"

table_columns_visible:
  "Bcftools: Stats": false

module_order:
  - 'fastp'
  - 'picard'
  - 'samtools'
  - 'bcftools'

remove_sections:
  - bcftools-stats_indel_plot

extra_fn_clean_exts:
  - ".alignment"
  - ".base_distribution_by_cycle"
  - ".dedup"
  - ".gcbias_detail"
  - ".gcbias_summary"
  - ".insert_size"
  - ".mean_quality_by_cycle"
  - ".quality_yield"
  - ".qualityscore"

fastp:
  s_name_filenames: true

table_sample_merge:
  "Lane 1":  "_L001"
  "Lane 2":  "_L002"
  "Lane 3":  "_L003"
  "Lane 4":  "_L004"
  "Lane 5":  "_L005"
  "Lane 6":  "_L006"
  "Lane 7":  "_L007"
  "Lane 8":  "_L008"
  "Lane 9":  "_L009"
  "Lane 10": "_L010"
  "Lane 11": "_L011"
  "Lane 12": "_L012"
  "Lane 13": "_L013"
  "Lane 14": "_L014"
  "Lane 15": "_L015"
  "Lane 16": "_L016"
  "Lane 17": "_L017"
  "Lane 18": "_L018"
  "Lane 19": "_L019"
  "Lane 20": "_L020"

picard_config:
  s_name_filenames: true

software_versions:
  "Read pre-processing":
    seqkit: "2.10.0"
    fastp: "0.24.0"
  "Read aligning":
    clara-parabricks: "4.5.0-1"
    samtools: "1.17"
  "Variant calling":
    bedtools: "2.30.0"
    bcftools: "1.17"
  "Variant filtering":
    bcftools: "1.17"
    vcftools: "0.1.16"

disable_version_detection: true
